### ISSUE TITLE
pycaret dependency

### ISSUE THREAD

**Issue by fbrausse** [fbrausse/smlp#32]
> Pycaret only supports python 3.9, 3.10, 3.11.
> 
> Seems to me pycaret is no longer actively maintained. Last commit to their master branch was in March 2025 and already [back in Nov 2024](https://github.com/pycaret/pycaret/discussions/4087) people noticed the dev team not working on it anymore. We need to replace this dependency of SMLP. 

 _Originally posted by @fbrausse in [#31](https://github.com/SMLP-Systems/smlp/issues/31#issuecomment-3616159274)_

@zurabksmlp Do you know what would be affected in SMLP by removing the pycaret dependency?

**Comment by mdmitry1** [comment]
Google recommendation is to replace pycaret by [AutoGluon](https://pypi.org/project/autogluon) .

**Comment by mdmitry1** [comment]
Evaluated AutoGluon and has been disappointed - worse modeling accuracy and slower inference on [Shekel](https://www.sfu.ca/~ssurjano/shekel.html) test. Conclusion so far - it is not a valid replacement for pycaret.

**Comment by fbrausse** [comment]
This issue has not been resolved. Pycaret-3.4.0 is still a dependency.

**Comment by mdmitry1** [comment]
There is no need to remove `pycaret`. Solution for `python3.12` is to replace pycaret by `pycaret-ni`. This should be good enough for the latest Ubuntu version `26.04`. There is new maintainer and work on solution for `python3.13`  is in progress.

Here is the wheel:

```
=== 1. Run 26595558333 [smlp_python312]: Build ===
  attempt 1 [by: mdmitry1] [started: 2026-05-28 21:54:52 IDT] [finished: 2026-05-28 22:15:02 IDT]:
    smlptech-1.3.8rc9-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl
```

Above wheel links with `Z3` `4.16.0`. I've tried to build also `Z3` `4.8.12`, but `Z3` compilation failed on `python3.12`.
Error message:

```
  Traceback (most recent call last):
    File "/root/z3/z3-z3-4.8.12/scripts/mk_make.py", line 9, in <module>
      from mk_util import *
    File "/root/z3/z3-z3-4.8.12/scripts/mk_util.py", line 18, in <module>
      import distutils.sysconfig
  ModuleNotFoundError: No module named 'distutils'
```

In parallel, I've build a wheel, which links with `Z3` `4.8.12` using Docker and `Z3` python package with the same tag and it passed regression:
[https://test.pypi.org/project/smlptech/1.3.0rc5](https://test.pypi.org/project/smlptech/1.3.0rc5/) .

**Comment by fbrausse** [comment]
> Solution for `python3.12` is to replace pycaret by `pycaret-ni`. This should be good enough for the latest Ubuntu version `26.04`.

Sorry, I don't understand what our pycaret dependency has to do with Ubuntu, or are you talking specifically about Python-3.12 (independent of this particular issue)?

> There is new maintainer and work on solution for `python3.13` is in progress.

I've not been able to confirm any of that. Please, if you have one, do provide a link. From what I see about `pycaret-ni`, it consistently links to the original `pycaret` project (on Github, as well as its (former?) team there). `pycaret-ni` does not seem to exist as a separate project and `pycaret` itself wants to revamp everything with the 4.0 release and entire 4.x roadmap, see their readme and docs linked therein: https://github.com/pycaret/pycaret

From what I gather there, they have no plans to support the 3.x API in the future, so we still should get rid of it (or switch to their 4.x API).

**Comment by mdmitry1** [comment]
1) [pycaret-ni 3.4.0](https://pypi.org/project/pycaret-ni)
    Passed SMLP regression on python3.12 with no diffs for almost all tests and with minimal diffs on several tests.
2) [pycaret 4.0.0a8](https://pypi.org/project/pycaret/4.0.0a8)
3) Double-checking on Docker `Ubuntu 26.04`  image showed that [https://ppa.launchpadcontent.net/deadsnakes](https://ppa.launchpadcontent.net/deadsnakes) has `python3.11`, `python3.12` and `python3.13` already.
  
Based on above information I believe we should keep working with `pycaret`.
Next milestone will be in August, when `Ubuntu 24.04`->`Ubuntu 26.04` upgrade will become available and I'll migrate my machine to native `Ubuntu 26.04` .

**Comment by fbrausse** [comment]
@mdmitry1 Could you please start answering questions or try to explain yourself better. My questions were pretty specific and your reply has nothing to do with them. Here, again:
- What does Ubuntu have to do with pycaret?
- Your suggestion `pycaret-ni` seems to just be the same as pycaret, version 3.x of which will no longer be supported. Why do you think it would be "good enough" for anything moving forward, and for what in particular?
- You claim something about new maintainership and some opaque "solution" for python3.13. Solution to what and where are you getting that "information"?

**Comment by fbrausse** [comment]
Based on your latest reply I have another question: what "next milestone" are you referring to?

**Comment by mdmitry1** [comment]
1) What does Ubuntu have to do with pycaret?
   If `python3.11` will be discontinued on [https://ppa.launchpadcontent.net/deadsnakes](https://ppa.launchpadcontent.net/deadsnakes) for `Ubuntu 26.04` then there will be a need to compile `python3.11`  in order to use `pycaret=3.3.2`.
2) `pycaret-ni` supports `python3.12`, while  `pycaret=3.3.2` does not. Our regression passed.
3) One solution for `python3.13` just works - it passed our regression. 
     I've build it myself from pycaret branch, which has built specifically for this purpose.
    Branch name is `feature/updating-to-python-3.13`.
    Another solution is `4.0.0`, alpha version is already available. I believe it means that there is a maintainer. 
   At least in this  context by maintainer I mean person, developing `pycaret==4.0.0`.
4) Next milestone - I'll be able to upgrade my machine to `Ubuntu 26.04.*`.
    The first release, supporting upgrade is `26.04.1`.
    Until then I have no technical possibility to build and test SMLP on this version.
    Currently there is only Docker image. 

### Bottom line 
Currently I don't see strong incentive to remove `pycaret` dependency. I guess there won't be too many customers who will replace `Ubuntu 24.04` by `Ubuntu 26.04` before upgrade path will become available.  

Reference for 4. - see the last line in the table below.

[Ubuntu 26.04: Release Date and New Features in Resolute Raccoon](https://linuxconfig.org/ubuntu-26-04-release-date-and-new-features-in-resolute-raccoon)

| Feature | Details |
|---|---|
| Release Date | April 23, 2026 |
| Desktop Environment | GNOME 50 (Wayland-only session) |
| Core Utilities | Rust-based (sudo-rs, uutils/coreutils) |
| Init System | systemd 259 (cgroup v2 only) |
| New Default Apps | Resources (system monitor), GIMP 3.2 |
| Point Release | August 6, 2026 (26.04.1) |

**Comment by fbrausse** [comment]
Thanks for clarifying.

[pycaret-ni](https://pypi.org/project/pycaret-ni/), as well as [pycaret-core](https://pypi.org/project/pycaret-core/), the difference between which is not clear to me, appear to be based on an [unofficial fork](https://github.com/pycaret/pycaret/issues/4119#issuecomment-2645988736) uploaded by someone whose maintainership of pycaret itself [has been denied](https://github.com/pycaret/pycaret/issues/4119#issuecomment-2646041381) at the same time those uploads to PyPI were made.

You said about pycaret-ni:
> Passed SMLP regression on python3.12 with no diffs for almost all tests and with minimal diffs on several tests.

What does "with minimal diffs on several tests" mean? Are these diffs significant? Ideally, there should be no diffs. Maybe those diffs are caused by merely switching to python3.12 and they are independent of pycaret vs. pycaret-ni. Did you test pycaret-ni on python3.11 as well?

We cannot "just switch" our dependency to a potentially unmaintained and unofficial fork.

To me, if we want to keep the code depending on pycaret, the only way forward is migrating to the new (apparently now maintained) 4.x development of pycaret, which, according to their own docs, is a complete rewrite including their API. For that we should wait until the first stable release. According to their current [roadmap](https://github.com/pycaret/pycaret/blob/main/docs/revamp/ROADMAP.md), they plan to support python3.11 and up with 4.x and they have a migration guide from 3.x to 4.x: https://pycaret.org/docs/guides/migrating-from-3-x

As a side note: Ubuntu-26.04 support for SMLP is a different issue, let's not mix these. Maybe create a new issue and reference this one there.

**Comment by mdmitry1** [comment]
Diffs are unrelated to pycaret. They are caused by switching to keras 3 and tensorflow 2.21.0.
This is needed, as python 3.12 does not support older versions of keras and tensorflow.

I'll open a new issue for Ubuntu 26.04 .
However, I don't see enough motivation to do move to newer python versions on Ubuntu 24.04.

The largest diff:

```
diff Test13_smlp_toy_basic.txt ../master/ | grep msqe
```

```
< smlp_logger - INFO - Prediction on training data --  msqe: 38.795
> smlp_logger - INFO - Prediction on training data --  msqe: 41.749
< smlp_logger - INFO - Prediction on test data --  msqe: 11.661
> smlp_logger - INFO - Prediction on test data --  msqe: 11.659
< smlp_logger - INFO - Prediction on labeled data --  msqe: 33.368
> smlp_logger - INFO - Prediction on labeled data --  msqe: 35.731
```

**Comment by fbrausse** [comment]
> However, I don't see enough motivation to do move to newer python versions on Ubuntu 24.04.

Personally, I don't care much about Ubuntu. I do care about supporting different versions of Python. The latter should enable the former.

**Comment by mdmitry1** [comment]
`python3.12` support is almost ready in my draft PR.
Main issue will be code review, as keras 3 interface significantly differs from keras 2.
Backward compatibility is preserved.
If we decide that it worth the effort, I'll finish this PR and submit for review.
